dhoran_nepal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += [
                   path("ckeditor5/", include('django_ckeditor_5.urls')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/details/<str:id>', views.product_details, name='product_details'),
    path('search/product/', views.ProductSearch.as_view(), name='search'),
    path('mycart/', views.my_cart, name='cart'),
    path('esewa/success/', views.esewa_success, name='esewa_success'),
    path('my_order/', views.my_order, name='my_order'),
    path('order_details/<str:orderid>',
         views.view_order_details, name='view_order_details'),
    path('customer_product/', views.view_customer_product,
         name='view_customer_product'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # product category
    path('list/category/', views.ProductCategoriesListView.as_view(), name='categories_list'),
    path('create/category/', views.ProductCategoriesCreatView.as_view(), name='categories_create'),
    path('update/category/<str:pk>', views.ProductCategoryUpdateView.as_view(), name='update_category'),
    path('delete/category/<str:pk>', views.ProductCategoryDeleteView.as_view(), name='delete_category'),

    # product
    path('list/', views.ProductListView.as_view(), name='product_list'),
    path('create/', views.ProductCreateView.as_view(), name='product_create'),
    path('update/product/<str:pk>', views.ProductUpdateView.as_view(), name='product_update'),
    path('delete/product/<str:pk>', views.ProductDeleteView.as_view(), name='delete_product'),

    path('addto/cart/<str:pk>/',views.add_to_cart,name="add_to_cart"),
    path('order/',views.my_order,name="order_list"),
    path('order_details/<str:orderid>', views.view_order_details, name='view_order_details'),
    path('send_item/<str:orderid>', views.send_item, name='send_item'),
    path('delivered/<str:orderid>', views.item_delivered, name='item_delivered'),


]

products/models.py
from itertools import product
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field

from accounts.models import CustomUser


# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Condition(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    user = models.ForeignKey(
        CustomUser, on_delete=models.PROTECT, null=True, blank=True)
    photo = models.ImageField(
        upload_to='products/image/', verbose_name='Product Image')
    name = models.CharField(max_length=100, verbose_name='Product Name')
    categories = models.ManyToManyField(Categories, verbose_name='Categories')
    tags = models.CharField(max_length=500, blank=True,
                            null=True, verbose_name='Product Tags')
    price = models.PositiveIntegerField(verbose_name='Price')
    description = CKEditor5Field('Description', config_name='extends')
    stock = models.PositiveIntegerField(verbose_name='Total Stock')
    condition = models.ForeignKey(
        Condition, on_delete=models.CASCADE, verbose_name='Product Current Condition')
    total_sales = models.PositiveBigIntegerField(default=0)
    create_date = models.DateField(auto_now=True)
    total_click = models.PositiveIntegerField(default=0)
    is_available = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class MyOrder(models.Model):
    my_user = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, verbose_name='my_user', null=True)
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, verbose_name='my_product', null=True)
    quantity = models.IntegerField(default=1)
    is_paid = models.BooleanField(default=False)
    txid = models.CharField(max_length=100, blank=True, null=True)
    order_id = models.CharField(max_length=100, blank=True, null=True)
    is_order_placed = models.BooleanField(default=False)
    is_order_sent = models.BooleanField(default=False)
    is_order_delivered = models.BooleanField(default=False)

products/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget

from .models import Condition, Categories, Product


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = '__all__'


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'user', 'photo', 'name', 'categories', 'description', 'price', 'stock', 'condition'
        ]

    def __init__(self, user=None, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user'].initial = user
        self.fields['user'].widget = forms.HiddenInput()

        # widgets = {
        #     "description": CKEditor5Widget(
        #         attrs={"class": "django_ckeditor_5"}, config_name="extends"
        #     )
        # }

products/views.py
from itertools import product
from socket import fromfd
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.http import Http404
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .forms import CategoryForm, ProductForm
from products.models import Categories, MyOrder, Product
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.db.models import F, Q, Sum

from django.contrib.auth.decorators import login_required

# listing product categories


class ProductCategoriesListView(ListView):
    model = Categories
    context_object_name = 'categories'
    template_name = 'products/categories/list_categories.html'


# creating product categories
class ProductCategoriesCreatView(SuccessMessageMixin, CreateView):
    form_class = CategoryForm
    template_name = 'products/categories/create_categories.html'
    success_message = 'Product Categories Created Successfully'

    def get_success_url(self):
        return reverse_lazy('product:categories_list')


# updating product categories
class ProductCategoryUpdateView(SuccessMessageMixin, UpdateView):
    form_class = CategoryForm
    model = Categories
    template_name = 'products/categories/update_categories.html'
    success_message = 'Product Category Updated Successfully'

    def get_success_url(self):
        return reverse_lazy('product:categories_list')


# deleting product categories
class ProductCategoryDeleteView(SuccessMessageMixin, DeleteView):
    # specify the model you want to use
    model = Categories
    success_message = 'Product Category Updated Successfully'
    template_name = "products/categories/delete_category.html"

    def get_success_url(self):
        return reverse_lazy('product:categories_list')


# listing product categories
class ProductListView(ListView):
    model = Product
    context_object_name = 'products'
    template_name = 'products/product/product_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            queryset = Product.objects.filter(
                Q(user=None) | Q(user__is_superuser=True))
        else:
            queryset = Product.objects.filter(user=self.request.user)
        return queryset


# creating product
class ProductCreateView(SuccessMessageMixin, CreateView):
    form_class = ProductForm
    template_name = 'products/product/create_product.html'
    success_message = 'Product Categories Created Successfully'

    def get_success_url(self):
        return reverse_lazy('product:product_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

# updating product categories


class ProductUpdateView(SuccessMessageMixin, UpdateView):
    form_class = ProductForm
    model = Product
    template_name = 'products/product/update_product.html'
    success_message = 'Product Updated Successfully'

    def get_success_url(self):
        return reverse_lazy('product:product_list')


# deleting product categories
class ProductDeleteView(SuccessMessageMixin, DeleteView):
    # specify the model you want to use
    model = Product
    success_message = 'Product Deleted Successfully'
    template_name = "products/product/delete_product.html"

    def get_success_url(self):
        return reverse_lazy('product:product_list')


def add_to_cart(request, pk):
    try:
        user = request.user
        product = Product.objects.get(pk=pk)

        my_order = MyOrder.objects.filter(
            my_user=user, product=product, is_paid=False)
        if my_order.exists():
            my_order.update(quantity=F('quantity') +
                            request.GET.get('quantity', 1))
        else:
            my_cart = MyOrder(
                my_user=user,
                product=product,
                quantity=request.GET.get('quantity', 1)
            )
            my_cart.save()
            messages.success(request,
                             f'Added To cart.')
    except Exception as e:
        print(e)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required()
def my_order(request):
    my_order = MyOrder.objects.filter(is_paid=True)
    rewards_point = my_order.aggregate(
        Total=(Sum('product__price') / 1000))['Total']
    print(my_order.aggregate(Total=(Sum('product__price'))))
    orders = set(
        my_order.values_list('order_id', 'is_paid', 'is_order_sent', 'is_order_delivered'))
    context = {'my_orders': orders, 'rewards_point': rewards_point}
    return render(request, 'products/my_order.html', context)


@login_required()
def view_order_details(request, orderid):
    order_details = MyOrder.objects.filter(order_id=orderid)
    context = {'my_orders': order_details}
    return render(request, 'products/order_details.html', context)


@login_required()
def send_item(request, orderid):
    MyOrder.objects.filter(order_id=orderid).update(is_order_sent=True)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required()
def item_delivered(request, orderid):
    MyOrder.objects.filter(order_id=orderid).update(is_order_delivered=True)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

products/templates/products/product/create_product.html
{% extends 'form_base.html' %}
{% block title %}Create Product{% endblock %}
{% block pagetitle %}Create Product{% endblock %}
{% block body %}
    {% if form.errors %}{{ form.errors }}{% endif %}
    <form method="post" action="{% url 'product:product_create'%}" novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input value="Create Product" class="btn btn-success" type="submit">
    </form>
    
{% endblock %}

products/templates/products/product/delete_product.html
<form method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

<a href="{% url 'product:product_list' %}">Cancel</a>

products/templates/products/product/product_list.html
{% extends 'datatable_base.html' %}
{% load static %}
{% block title %}Product{% endblock %}
{% block pagetitle %}Product{% endblock %}
{% block addbutton %}
    <a href="{% url 'product:product_create' %}"
       class="btn btn-sm btn-secondary mx-0 shadow-sm float-right">
        <i class="fas fa-plus"></i> Add Product
    </a>
{% endblock %}
{% block table %}
    <div class="box-content">
        
            <!-- /.dropdown js__dropdown -->
            <div class="table-responsive">
                <table id="example" class="display compact nowrap" style="width:100%">
                    <thead>
                    <tr>
                      <th>Name</th>
                      <th>Photo</th>
                
                      <th>Categories</th>
                
                      <th>Price</th>
                
                      <th>Stock</th>
                
                    <th>Action</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                      <th>Name</th>
                      <th>Photo</th>
                
                      <th>Categories</th>
                
                      <th>Price</th>
                
                      <th>Stock</th>
                
                    <th>Action</th>
                    </tr>
                    </tfoot>
                    <tbody>
                      {% for product in products %}
                      <tr>
                          <td>{{ product.name }}</td>
                          <td><img src="{{ product.photo.url }}" width="120" height="100"></td>
                          <td>-- {% for cat in product.categories.all %}{{ cat.name }}&nbsp;--{% endfor %}</td>
                          <td>{{ product.price }}</td>
                          <td>{{ product.stock }}</td>
                          <td>
                              <a class="btn btn-warning" href="{% url 'product:product_update' product.pk %}">Edit</a>&nbsp;
                              <a class="btn btn-danger" href="{% url 'product:delete_product' product.pk %}">Delete</a>
                          </td>
                      </tr>
                  {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/products/product/update_product.html
{% extends 'form_base.html' %}
{% block title %}Update Product{% endblock %}
{% block pagetitle %}Update Product{% endblock %}
{% block body %}
    {% if form.errors %}{{ form.errors }}{% endif %}
    <form method="post"  novalidate enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input value="Update Product" class="btn btn-success" type="submit">
    </form>
{% endblock %}