accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>',views.view_profile,name="profile")
]

dhoran_nepal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += [
                   path("ckeditor5/", include('django_ckeditor_5.urls')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/details/<str:id>', views.product_details, name='product_details'),
    path('search/product/', views.ProductSearch.as_view(), name='search'),
    path('mycart/', views.my_cart, name='cart'),
    path('esewa/success/', views.esewa_success, name='esewa_success'),
    path('my_order/', views.my_order, name='my_order'),
    path('order_details/<str:orderid>',
         views.view_order_details, name='view_order_details'),
    path('customer_product/', views.view_customer_product,
         name='view_customer_product'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # product category
    path('list/category/', views.ProductCategoriesListView.as_view(), name='categories_list'),
    path('create/category/', views.ProductCategoriesCreatView.as_view(), name='categories_create'),
    path('update/category/<str:pk>', views.ProductCategoryUpdateView.as_view(), name='update_category'),
    path('delete/category/<str:pk>', views.ProductCategoryDeleteView.as_view(), name='delete_category'),

    # product
    path('list/', views.ProductListView.as_view(), name='product_list'),
    path('create/', views.ProductCreateView.as_view(), name='product_create'),
    path('update/product/<str:pk>', views.ProductUpdateView.as_view(), name='product_update'),
    path('delete/product/<str:pk>', views.ProductDeleteView.as_view(), name='delete_product'),

    path('addto/cart/<str:pk>/',views.add_to_cart,name="add_to_cart"),
    path('order/',views.my_order,name="order_list"),
    path('order_details/<str:orderid>', views.view_order_details, name='view_order_details'),
    path('send_item/<str:orderid>', views.send_item, name='send_item'),
    path('delivered/<str:orderid>', views.item_delivered, name='item_delivered'),


]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import requests as req
import uuid
from django.shortcuts import render, redirect, HttpResponse
from products.models import Categories, MyOrder, Product
from django.http import Http404
from django.views.generic import ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required

from django.db.models import F, Q, Sum

# Create your views here.


def home(request):
    all_product = Product.objects.filter(is_available=True).all()
    context = {
        "active_nav": "home",
        "best_sellers": all_product.order_by('-total_sales')[:8],
        "new_arrivals": all_product.order_by('-create_date')[:8],
        "trending": all_product.order_by('total_click')[:8]
    }
    return render(request, 'home/home.html', context)


@login_required
def my_cart(request):
    oid = uuid.uuid4()
    products = MyOrder.objects.filter(my_user=request.user, is_paid=False)
    products.update(order_id=oid)
    total = 0
    for product in products:
        product_price = product.quantity*product.product.price
        total += product_price
    context = {
        "products": products,
        "total": total,
        "pid": oid
    }
    return render(request, 'home/cart.html', context)


def product_details(request, id):

    # try:
    product = Product.objects.get(id=id)

    # print(product.categories.all())
    try:
        related_product = Product.objects.filter(
            categories__in=product.categories.all()).exclude(pk=product.pk)[:4]
    except:
        related_product = None
    context = {
        "product": product,
        "realated_products": related_product
    }
    return render(request, 'home/product_details.html', context)


# class AllProductListView(ListView):
#     model = Product
#     template_name = "home/all_product.html"
#     paginate_by = 9
#     context_object_name="products"


class ProductSearch(ListView):
    model = Product
    template_name = "home/search.html"
    paginate_by = 9
    context_object_name = 'products'

    def get_queryset(self, *args, **kwargs):
        search_parameter = self.request.GET.get('search')
        price_range = self.request.GET.get('price')
        category = self.request.GET.get('categories')
        sorting = self.request.GET.get('sorting')

        all_product = Product.objects.all().order_by('total_click')

        if search_parameter:
            all_product = all_product.filter(Q(name__icontains=search_parameter) | Q(
                categories__name__icontains=search_parameter) | Q(tags__icontains=search_parameter))

        if price_range:
            if price_range == '1':
                print(price_range)
                all_product = all_product.filter(price__gt=0, price__lte=500)
            elif price_range == '2':
                all_product = all_product.filter(
                    price__gt=500, price__lte=1000)
            elif price_range == '3':
                all_product = all_product.filter(
                    price__gt=1000, price__lte=5000)
            elif price_range == '4':
                all_product = all_product.filter(
                    price__gt=5000, price__lte=10000)
            elif price_range == '5':
                all_product = all_product.filter(price__gte=10000)

        if category:
            all_product = all_product.filter(
                categories__name__icontains=category)

        if sorting:
            if sorting == 'low':
                all_product = all_product.order_by('price')
            elif sorting == 'high':
                all_product = all_product.order_by('-price')

        return all_product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Categories.objects.all()
        context["search"] = self.request.GET.get('search', '')
        context["mycategory"] = self.request.GET.get('categories', '')
        context["myprice"] = self.request.GET.get('price', '')
        context['mysorting'] = self.request.GET.get('sorting', '')
        return context


def esewa_success(request):

    import xml.etree.ElementTree as ET
    data = request.GET.copy()
    url = "https://uat.esewa.com.np/epay/transrec"

    d = {
        'amt': data['amt'],
        'scd': 'EPAYTEST',
        'rid': data['refId'],
        'pid': data['oid'],
    }

    resp = req.post(url, d)
    root = ET.fromstring(resp.content)
    status = root[0].text.strip()

    if status == 'Success':

        MyOrder.objects.filter(
            order_id=data['oid']
        ).update(
            is_paid=True
        )
        return redirect(f'/order_details/{data["oid"]}')
    else:
        return HttpResponse('failure')


@login_required()
def my_order(request):
    my_order = MyOrder.objects.filter(
        my_user=request.user).filter(is_paid=True)
    rewards_point = my_order.aggregate(
        Total=(Sum('product__price') / 1000))['Total']
    print(my_order.aggregate(Total=(Sum('product__price'))))
    orders = set(
        my_order.values_list('order_id', 'is_paid', 'is_order_sent', 'is_order_delivered'))
    context = {'my_orders': orders, 'rewards_point': rewards_point}
    return render(request, 'home/my_order.html', context)


@login_required()
def view_order_details(request, orderid):
    order_details = MyOrder.objects.filter(
        order_id=orderid).filter(my_user=request.user)
    context = {'my_orders': order_details}
    return render(request, 'home/order_details.html', context)


def view_customer_product(request):
    context = {
        'products': Product.objects.filter(is_available=True).filter(user__is_superuser=False).filter(stock__gt=0).order_by('-create_date'),
        "categories": Categories.objects.all()
    }
    return render(request, 'home/search.html', context)

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dhoran Nepal</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'landing/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'landing/css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__option">
            {% if not request.user.is_authenticated %}

            <div class="offcanvas__links">
                <a href="{%url 'accounts:login'%}">Sign in</a>     
            </div>
            {%else%}
            <div class="offcanvas__top__hover">
                <span>Profile <i class="arrow_carrot-down"></i></span>
                                <ul>

                                    <a href="{% url 'product:product_list' %}"><li>Dashboard</li></a>

                                    

                                    <a href="{% url 'accounts:logout' %}"><li>Logout</li></a>
                </ul>
            </div>
            {% endif %}

            
        </div>
        
        <div class="offcanvas__nav__option">
            <a href="#" class="search-switch"><img src="{% static 'landing/img/icon/search.png' %}" alt=""></a>
            <a href="{% url 'home:my_order' %}"><img src="{% static 'landing/img/icon/heart.png' %}" alt=""></a>
            <a href="{% url 'home:cart' %}"><img src="{% static 'landing/img/icon/cart.png' %}" alt=""> <span>0</span></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__text">
            <p>Free shipping, Anywhere in Kathmandu.</p>
            
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-7">
                        <div class="header__top__left">
                            <p>Free shipping, Anywhere in Kathmandu.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-5">
                        <div class="header__top__right">
                            {% if not request.user.is_authenticated %}
                            <div class="header__top__links">
                                
                <a href="{%url 'accounts:login'%}">Sign in</a>     
    
                            </div>
                            {%else%}
                            <div class="header__top__hover">
                                <span>Profile <i class="arrow_carrot-down"></i></span>
                                <ul>
                                    
                                    <a href="{% url 'product:product_list' %}"><li>Dashboard</li></a>

                                    
                                    <a href="{% url 'accounts:logout' %}"><li>Logout</li></a>
                                </ul>
                            </div>
                            {% endif %}

                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
        {% if message%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {%endif%}
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="header__logo">
                        <h3>Dhoran Nepal <span style="color:red;">.</style></h3>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="/">Home</a></li>
                            <li><a href="{% url 'home:search' %}">All Clothes</a></li>
                            <li><a href="{% url 'home:view_customer_product' %}">Customer's Product</a></li>
                        </ul>
                    </nav>
                </div>
                
                
                <div class="col-lg-3 col-md-3">
                    <div class="header__nav__option">
                        <a href="#" class="search-switch"><img src="{% static 'landing/img/icon/search.png' %}" alt=""></a>
                        <a href="{% url 'home:my_order' %}"><img src="{% static 'landing/img/icon/heart.png' %}" alt=""></a>
                        <a href="{% url 'home:cart' %}"><img src="{% static 'landing/img/icon/cart.png' %}" alt=""></a>
                    </div>
                </div>
                {%block cust%}
                {%endblock%}
                
            </div>
            <div class="canvas__open"><i class="fa fa-bars"></i></div>
        </div>
    </header>
    <!-- Header Section End -->

    {% block body %}
    
    {% endblock body %}}

   

    <!-- Latest Blog Section Begin -->
    <section class="latest spad">
        
    </section>
    <!-- Latest Blog Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <h2 style="color:white;">Dhoran Nepal <span style="color:red;">.</span></h2>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes Everything.</p>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Clothes</h6>
                        <ul>
                            <li><a href="/search/product/?search=sari">Sari</a></li>
                            <li><a href="/search/product/?search=coat">Coat</a></li>
                            <li><a href="/search/product/?search=tshirt">T-Shirt</a></li>
                            <li><a href="/search/product/?search=pant">Pant</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <ul>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Dhoran Nepal can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>2020
                            All rights reserved  by <a href="#" target="_blank">Dhoran Nepal</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form" method="get" action="{% url 'home:search' %}">
                <input type="text" id="search-input" value="{{search}}" name="search" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'landing/js/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'landing/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'landing/js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'landing/js/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'landing/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'landing/js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'landing/js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'landing/js/mixitup.min.js'%}"></script>
    <script src="{% static 'landing/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'landing/js/main.js'%}"></script>

    <script>
        $(document).ready(function (e) {
            $(".new-arrivals").hide()
            $(".hot-sales").hide()
        });
    </script>
</body>

</html>

home/templates/home/home.html
{% extends 'home/base.html' %}
{% load static %}

{% block body %}

 <!-- Hero Section Begin -->
 <section class="hero">
    <div class="hero__slider owl-carousel">
        <div class="hero__items set-bg" data-setbg="{% static 'landing/img/hero/hero-1.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Summer Collection</h6>
                            <h2>Our Summer Collection</h2>
                            <p>Checkout our summer collection colthes. Buy to save the our planet.</p>
                            <a href="/search/product/?search=summer" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
                                <a href="https://instagram.com/"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="hero__items set-bg" data-setbg="{% static 'landing/img/hero/hero-2.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-7 col-md-8">
                        <div class="hero__text">
                            <h6>Winter Collection</h6>
                            <h2>Our - Winter Collections</h2>
                            <p>Used Cothes like Brand New. Ethically crafted with an unwavering
                            commitment to exceptional quality.</p>
                            <a href="/search/product/?search=winter" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                            <div class="hero__social">
                                <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                                <a href="https://twitter.com/"><i class="fa fa-twitter"></i></a>
                                <a href="https://instagram.com/"><i class="fa fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

<!-- Banner Section Begin -->
<section class="banner spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-4">
                <div class="banner__item">
                    <div class="banner__item__pic">
                        <img src="{% static 'landing/img/banner/banner-1.jpg' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>T-Shirt Collections -2023</h2>
                        <a href="/search/product/?search=tshirt">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="banner__item banner__item--middle">
                    <div class="banner__item__pic">
                        <img src="{% static 'landing/img/sari.png' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Sari</h2>
                        <a href="/search/product/?search=sari">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-7">
                <div class="banner__item banner__item--last">
                    <div class="banner__item__pic">
                        <img src="{% static 'landing/img/coat.png' %}" alt="">
                    </div>
                    <div class="banner__item__text">
                        <h2>Latest Coat Collection</h2>
                        <a href="/search/product/?search=coat">Shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Banner Section End -->

<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="filter__controls">
                    <li class="active" data-filter=".best-seller" id="bestest">Best Sellers</li>
                    <li data-filter=".new-arrivals">New Arrivals</li>
                    <li data-filter=".hot-sales">Trending</li>
                </ul>
            </div>
        </div>
        <div class="row product__filter">
            {% for product in best_sellers%}
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix best-seller">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="{{product.photo.url}}">
                        {% comment %} <span class="label">New</span> {% endcomment %}
                        <ul class="product__hover">
                            <li><a href="#"><img src="{% static 'landing/img/icon/heart.png' %}" alt=""><span>Add to wishlist</span></a></li>
                            <li><a href="{% url 'product:add_to_cart' product.pk %}"><img src="{% static 'landing/img/icon/cart.png' %}" alt=""> <span>Add to cart</span></a></li>
                            {% comment %} <li><a href="#"><img src="{% static 'landing/img/icon/search.png' %}" alt=""></a></li> {% endcomment %}
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6>{{product.name}}</h6>
                        <a href="{% url 'home:product_details' product.pk %}" class="add-cart"><i class="fa fa-eye"></i> View</a>
                        
                        <h5>रु {{product.price}}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% for product in new_arrivals%}
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix new-arrivals">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="{{product.photo.url}}">
                        {% comment %} <span class="label">New</span> {% endcomment %}
                        <ul class="product__hover">
                            <li><a href="#"><img src="{% static 'landing/img/icon/heart.png' %}" alt=""><span>Add to wishlist</span></a></li>
                            <li><a href="#"><img src="{% static 'landing/img/icon/cart.png' %}" alt=""> <span>Add to cart</span></a></li>
                            {% comment %} <li><a href="#"><img src="{% static 'landing/img/icon/search.png' %}" alt=""></a></li> {% endcomment %}
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6>{{product.name}}</h6>
                        <a href="{% url 'home:product_details' product.pk %}" class="add-cart"><i class="fa fa-eye"></i> View</a>
                        
                        <h5>रु {{product.price}}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% for product in trending%}
            <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix hot-sales">
                <div class="product__item">
                    <div class="product__item__pic set-bg" data-setbg="{{product.photo.url}}">
                        {% comment %} <span class="label">New</span> {% endcomment %}
                        <ul class="product__hover">
                            <li><a href="#"><img src="{% static 'landing/img/icon/heart.png' %}" alt=""><span>Add to wishlist</span></a></li>
                            <li><a href="#"><img src="{% static 'landing/img/icon/cart.png' %}" alt=""> <span>Add to cart</span></a></li>
                            {% comment %} <li><a href="#"><img src="{% static 'landing/img/icon/search.png' %}" alt=""></a></li> {% endcomment %}
                        </ul>
                    </div>
                    <div class="product__item__text">
                        <h6>{{product.name}}</h6>
                        <a href="{% url 'home:product_details' product.pk %}" class="add-cart"><i class="fa fa-eye"></i> View</a>                        
                        <h5>रु {{product.price}}</h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Product Section End -->

<!-- Categories Section Begin -->
<section class="categories spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="categories__text">
                    <h2>Clothings Hot <br /> <span>Bag Collection</span> <br /> Coat For Party</h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="categories__hot__deal">
                    <img src="{% static 'landing/img/product-sale.png' %}" alt="">
                    <div class="hot__deal__sticker">
                        <span>Best Used</span>
                        <h5>Cheap</h5>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1">
                <div class="categories__deal__countdown">
                    <span>Re-used Bag</span>
                    <h2>Used bag at cheap price</h2>
                    
                    <a href="/search/product/?search=bag" class="primary-btn">Shop now</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Categories Section End -->

<!-- Instagram Section Begin -->
<section class="instagram spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="instagram__pic">
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-1.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-2.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-3.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-4.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-5.jpg' %}"></div>
                    <div class="instagram__pic__item set-bg" data-setbg="{% static 'landing/img/instagram/instagram-6.jpg' %}"></div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="instagram__text">
                    <h2>Follow Us on</h2>
                    <p>We are also active on our instagram page. Please dont feel shy to text on instagram. We respond to your message as soon as possible</p>
                    <h3>#Dhoran_Nepal</h3>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Instagram Section End -->

{% endblock body %}