accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>',views.view_profile,name="profile")
]

dhoran_nepal/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('',include('home.urls')),
    path('accounts/',include('accounts.urls'))
]

urlpatterns += [
                   path("ckeditor5/", include('django_ckeditor_5.urls')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/details/<str:id>', views.product_details, name='product_details'),
    path('search/product/', views.ProductSearch.as_view(), name='search'),
    path('mycart/', views.my_cart, name='cart'),
    path('esewa/success/', views.esewa_success, name='esewa_success'),
    path('my_order/', views.my_order, name='my_order'),
    path('order_details/<str:orderid>',
         views.view_order_details, name='view_order_details'),
    path('customer_product/', views.view_customer_product,
         name='view_customer_product'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    # product category
    path('list/category/', views.ProductCategoriesListView.as_view(), name='categories_list'),
    path('create/category/', views.ProductCategoriesCreatView.as_view(), name='categories_create'),
    path('update/category/<str:pk>', views.ProductCategoryUpdateView.as_view(), name='update_category'),
    path('delete/category/<str:pk>', views.ProductCategoryDeleteView.as_view(), name='delete_category'),

    # product
    path('list/', views.ProductListView.as_view(), name='product_list'),
    path('create/', views.ProductCreateView.as_view(), name='product_create'),
    path('update/product/<str:pk>', views.ProductUpdateView.as_view(), name='product_update'),
    path('delete/product/<str:pk>', views.ProductDeleteView.as_view(), name='delete_product'),

    path('addto/cart/<str:pk>/',views.add_to_cart,name="add_to_cart"),
    path('order/',views.my_order,name="order_list"),
    path('order_details/<str:orderid>', views.view_order_details, name='view_order_details'),
    path('send_item/<str:orderid>', views.send_item, name='send_item'),
    path('delivered/<str:orderid>', views.item_delivered, name='item_delivered'),


]

templates/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<!-- <html lang="en" oncontextmenu="return false;"> -->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Home </title>

    <!-- Favicon -->
    <link href="{% static 'assets/images/logo.png' %}" rel="icon">

    <link rel="stylesheet" href="{% static 'assets/plugin/poppins_font/poppins_font.css' %}">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets/fonts/material-design/css/materialdesignicons.css' %}">
    <!-- Main Styles -->
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">

</head>

<body>

<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

{% include 'navbar.html' %}
<!-- /.main-menu -->

<div class="fixed-navbar">
    <div class="pull-left">
        <button type="button" class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
        <h1 class="page-title">Dashboard</h1>
        <!-- /.page-title -->
    </div>

    <!-- /.pull-left -->
</div>
<!-- /.fixed-navbar -->

<div id="wrapper">
    <div class="main-content">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                {% elif message.tags == 'errors' %}
                    <div class="alert alert-error alert-dismissible">
                {% endif %}
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        {% block body %}{% endblock %}


        </div>
        <!-- /.main-content -->
    </div>
    <!--/#wrapper -->


    <script src="{% static 'assets/scripts/all.min.js' %}"></script>
    <script src="{% static 'assets/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugin/nprogress/nprogress.js' %}"></script>
    <script src="{% static 'assets/scripts/main.js' %}"></script>
    

</body>

</html>

templates/datatable_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Raman Associates">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Favicon -->
    <!-- Favicon -->
    <link href="{% static 'assets//images/logo.png' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'assets//plugin/poppins_font/poppins_font.css' %}">
    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets//fonts/material-design/css/materialdesignicons.css' %}">

    <!-- Data Table -->
    <link rel="stylesheet" href="{% static 'assets//plugin/datatables/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets//plugin/datatables/responsive.dataTables.min.css' %}">
    <script src="{% static 'assets//scripts/jquery.min.js' %}"></script>
    <script src="{% static 'assets//plugin/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets//plugin/datatables/dataTables.responsive.min.js' %}"></script>
    <!-- End Datatable -->

    <link href="{% static 'assets//plugin/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'assets//style.css' %}">
    <script src="{% static 'assets/plugin/nepali-date-picker/nepali.datepicker.v3.7.min.js' %}"></script>


</head>

<body>

<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

{% include 'navbar.html' %}
<!-- /.main-menu -->
<div class="container">

</div>

<div class="fixed-navbar">
    <div class="pull-left">
        <button type="button"
                class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
        <h1 class="page-title">{% block pagetitle %}{% endblock %}</h1>
        <!-- /.page-title -->
    </div>
    <!-- /.pull-left -->
    <div class="pull-right">
        <div class="ico-item">
            {% block addbutton %}{% endblock %}
        </div>
        <!-- /.ico-item -->
    </div>

</div>
<!-- /.fixed-navbar -->

<div id="wrapper">
    <div class="main-content">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger alert-dismissible">
                {% endif %}
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
            </div>
            {% endfor %}
        {% endif %}

        <div class="row small-spacing">

            <div class="col-xs-12">

                {% block table %}{% endblock %}

                <style>
                    div.container {
                        max-width: 1200px;
                    }
                </style>
                <script>
                    $(document).ready(function () {
                        var table = $('#example').DataTable({
                            responsive: true,
                            paging: true,
                            orderClasses: true,
                            processing: true,
                        });
                    });
                </script>
                <!-- /.box-content -->
            </div>
            <!-- /.col-xs-12 -->
        </div>
        </div>
        <!-- /.main-content -->
    </div>
    <!--/#wrapper -->

    

    <script src="{% static 'assets/scripts/all.min.js' %}"></script>


    <script src="{% static 'assets/plugin/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/plugin/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/plugin/nprogress/nprogress.js' %}"></script>


    <!-- Data Tables -->

    <!-- <script src="https://code.jquery.com/jquery-3.5.1.js"></script> -->

    <script src="{% static 'assets/scripts/main.js' %}"></script>
    <script>
        $(function () {
            $.ajax({
                method: 'GET',
                url: '/media/new/notification/',
                beforeSend: function () {
                },
                success: function (total) {
                    console.log(total.total)
                    $("#new_notification").append('' + total.total);
                },

                error: function (er) {
                    console.log(er);
                }
            });
        });
    </script>

    {% block js %}

    {% endblock %}

</body>

</html>

templates/form_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Raman Associates">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'assets//images/logo.png' %}" rel="icon">

    <link rel="stylesheet" href="{% static 'assets//plugin/poppins_font/poppins_font.css' %}">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets//fonts/material-design/css/materialdesignicons.css' %}">

    <!-- Searchable Dropdown -->
    <link href="{% static 'assets/plugin/semantic/semantic.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'assets/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugin/semantic/semantic.min.js' %}"></script>
    <!-- Main Styles -->
    <link rel="stylesheet" href="{% static 'assets//style.css' %}">

<link href="{% static 'assets/plugin/nepali-date-picker/nepali.datepicker.v3.7.min.css' %}" rel="stylesheet" type="text/css" />

    <script src="{% static 'assets/plugin/nepali-date-picker/nepali.datepicker.v3.7.min.js' %}" type="text/javascript"></script>


    <style>
        hr {
            border: 1px solid var(--black);
        }
    </style>


</head>

<body>

<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

{% include 'navbar.html' %}
<!-- /.main-menu -->

<div class="fixed-navbar">
    <div class="pull-left">
        <button type="button"
                class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
        <h1 class="page-title">{% block pagetitle %}{% endblock %}</h1>
        <!-- /.page-title -->
    </div>
    <!-- /.pull-left -->
</div>
<!-- /.fixed-navbar -->

<div id="wrapper">

    <div class="main-content">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible">
                {% elif message.tags == 'errors' %}
                    <div class="alert alert-error alert-dismissible">
                {% endif %}
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        <div class="row small-spacing">
            <div class="col-xs-12">
                <div class="box-content">
                    {% block body %}
                    {% endblock %}
                    <!-- End Details -->
                    <script>
                        $('.ui.dropdown').dropdown();
                    </script>

                </div>

                <!-- /.box-content -->
            </div>

            <!-- /.col-xs-12 -->
        </div>


        </div>
    </div>
    <!-- /.main-content -->
    <!--/#wrapper -->

    <center>
        <footer class="footer">
			<ul class="list-inline">
				<li><span>Copyright &copy; Raman Associates,
						<script
							type="text/JavaScript"> var theDate=new Date(); document.write(theDate.getFullYear()) </script>
						<p class="developedby">Designed and Developed by, <a href="https://itnepalsolutions.com/"
								target="_blank" class="badge footer-badge">IT
								Nepal Solutions</a> &nbsp;&nbsp; <a class="badge footer-badge">Tech Beetle Technology</a></p>
					</span></li>

			</ul>
		</footer>
    </center>

    <script src="{% static 'assets/scripts/all.min.js' %}"></script>
    <script src="{% static 'assets/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'assets/plugin/nepali-date-picker/nepali-date-picker.min.js' %}"></script>

    <script>
        jQuery(document).ready(function () {
            $('.date-picker').nepaliDatePicker();
        })
    </script>

    <script src="{% static 'assets/plugin/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/plugin/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/plugin/nprogress/nprogress.js' %}"></script>
    <!-- Validator -->
    <script src="{% static 'assets/plugin/validator.min.js' %}"></script>

    <script src="{% static 'assets/scripts/main.js' %}"></script>
    <script>
        $(function () {
            $.ajax({
                method: 'GET',
                url: '/media/new/notification/',
                beforeSend: function () {
                },
                success: function (total) {
                    console.log(total.total)
                    $("#new_notification").append('' + total.total);
                },
                error: function (er) {
                    console.log(er);
                }
            });
        });
    </script>

</body>

</html>

templates/navbar.html
{% load static %}
<div class="main-menu">
    <header class="header">
        <a href="/" class="logo">
            Dhoran Nepal
        </a>
        <button type="button" class="button-close fa fa-times js__menu_close"></button>
        
        <!-- /.user -->
    </header>
    <!-- /.header -->
    <div class="content">
        <div class="navigation">
            <h5 class="title">Home</h5>
            <!-- /.title -->

            {% if request.user.is_superuser %}
            <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'product:product_list' %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>Product</span></a>
                    </li>
                </ul>

                <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'product:categories_list' %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>Categories</span></a>
                    </li>
                </ul>

                <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'product:order_list' %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>Order</span></a>
                    </li>
                </ul>
                {%else%}
                <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'accounts:profile' request.user %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>Profile</span></a>
                    </li>
                </ul>
                <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'product:product_list' %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>My Product</span></a>
                    </li>
                </ul>
                
                {% endif %}

                <ul class="menu js__accordion">
                    <li class="{% if active == 'dashboard' %}current{% endif %}">
                        <a class="" href="{% url 'accounts:logout' %}"><i class="menu-icon mdi mdi-view-dashboard"></i><span>Logout</span></a>
                    </li>
                </ul>
            

        </div>
        <!-- /.navigation -->
    </div>
    <!-- /.content -->
</div>

templates/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Raman Associates">
    <meta name="author" content="">

    <title>Notification - Raman Associates</title>

    <!-- Favicon -->
    <link href="{% static 'assets/images/logo.png'%}" rel="icon">

    <link rel="stylesheet" href="{% static 'assets/plugin/poppins_font/poppins_font.css'%}">

    <!-- Material Design Icon -->
    <link rel="stylesheet" href="{% static 'assets/fonts/material-design/css/materialdesignicons.css'%}">

    <link rel="stylesheet" href="{% static 'assets/plugin/bootstrap/css/bootstrap5.min.css'%}">

    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'assets/style.css'%}">
</head>

<body>
<style>
    sup {
        padding: 2px 5px;
        border-radius: 30%;
        background: var(--black);
        color: var(--white);
    }

    .notification .old-notify {
        background-color: var(--tertiary);
        color: var(--white);
    }

    .notification .new-notify {
        background-color: var(--black);
        color: var(--white);
    }

    .notification .old-notify a, .notification .new-notify a {
        color: var(--lightgray);
        text-decoration: underline;
    }
</style>
<!-- Back to top button -->
<button type="button" class="btn btn-primary btn-floating btn-sm" title="Back To Top" id="btn-back-to-top">
    <i class="fas fa-arrow-up"></i>
</button>

<div class="main-menu">
    <header class="header">
        <a href="index.html" class="logo">
            <span class="ico fa fa-gavel"></span> Raman Associates
        </a>
        <button type="button" class="button-close fa fa-times js__menu_close"></button>
        <div class="user">
            <a href="#" class="avatar"><img src="{% static 'assets/images/logo.png'%}" alt=""></a>
        </div>
        <!-- /.user -->
    </header>
    <!-- /.header -->
    <div class="content">
        <div class="navigation">
            <h5 class="title">Home</h5>
            <!-- /.title -->
            <ul class="menu js__accordion">
                <li class="">
                    <a class="" href="index.html"><i class="menu-icon mdi mdi-view-dashboard"></i><span>&nbsp;
                                Dashboard</span></a>
                </li>
            </ul>
            <!-- /.menu js__accordion -->
            <h5 class="title">Component</h5>
            <!-- /.title -->
            <ul class="menu js__accordion">
                <li class="current active">
                    <a class=" parent-item js__control" href="#"><i
                            class="menu-icon mdi mdi-file"></i><span>Pages</span><span
                            class="menu-arrow fa fa-angle-down"></span></a>
                    <ul class="sub-menu js__content">
                        <li><a href="tables-datatable.html"><i class="fa fa-table"></i> &nbsp; Data Table</a></li>
                        <li><a href="calendar.html"><i class="fa fa-calendar"></i> &nbsp;
                            Calendar</a>
                        </li>
                        <li><a href="404.html"><i class="fa fa-bug"></i> &nbsp; 404 Error</a></li>
                        <li><a href="form-validation.html"><i class="fa fa-book"></i> &nbsp; Form
                            Validation</a></li>
                        <li><a href="form.html"><i class="fa fa-book"></i> &nbsp; Form</a></li>
                        <li><a href="login.html"><i class="fa fa-lock"></i> &nbsp; Login</a></li>
                        <li class="current"><a href="#"><i class="fa fa-bell"></i> &nbsp; Notification
                            <sup>3</sup></a>
                        </li>
                    </ul>
                    <!-- /.sub-menu js__content -->
                </li>
            </ul>
            <!-- /.menu js__accordion -->
        </div>
        <!-- /.navigation -->
    </div>
    <!-- /.content -->
</div>
<!-- /.main-menu -->

<div class="fixed-navbar">
    <div class="pull-left">
        <button type="button"
                class="menu-mobile-button glyphicon glyphicon-menu-hamburger js__menu_mobile"></button>
        <h1 class="page-title">Notification</h1>
        <!-- /.page-title -->
    </div>
    <!-- /.pull-left -->
</div>
<!-- /.fixed-navbar -->

<div id="wrapper">
    <div class="main-content">
        <div class="notification container-fluid">

            <div class="row">
                <div class="col-md-4">
                    <div class="alert old-notify" style="border-right: 8px solid var(--danger)">
                        <i class="fa fa-bell"></i> &nbsp; Notification
                        <!-- <a href="">
                            Message.
                        </a> -->
                        <a class="btn btn-primary btn-sm" target="__blank" href="#">
                            <!-- <i class="fa fa-edit"></i> -->
                            Message
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert old-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        Message.</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert old-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        Message.</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="alert new-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification
                        <!-- <a href="">Message.</a> -->
                        <a class="btn btn-primary btn-sm" target="__blank" href="#">
                            <!-- <i class="fa fa-edit"></i> -->
                            Message
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert new-notify" style="border-left: 8px solid var(--danger)">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        <span class="badge">Message</span>
                    </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert new-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        Message.</a>
                    </div>
                </div>
            </div>

            <div class="old-notify alert" style="border-left: 8px solid var(--danger)">
                <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                Messages.</a>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="alert new-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        Messages.</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert new-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="">
                        Message.</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="alert new-notify">
                        <i class="fa fa-bell"></i> &nbsp; Notification <a href="" class="text-decoration-underline">
                        <i>Message</i></a>.
                    </div>
                </div>
            </div>
        </div>

        <nav aria-label="Page navigation example" class="text-center">
            <ul class="pagination shadow">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <!-- <span class="sr-only">Previous</span> -->
                    </a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <!-- <span class="sr-only">Next</span> -->
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- /.main-content -->
</div>
<!--/#wrapper -->

<footer class="sticky-footer bg-light">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
                <span>Copyright &copy; Raman Associates,
                    <script
                            type="text/JavaScript"> var theDate = new Date();
                    document.write(theDate.getFullYear()) </script>
                    <p class="developedby">Designed and Developed by, <a href="https://itnepalsolutions.com/"
                                                                         target="_blank">IT
                            Nepal Solutions</a></p>
                </span>
        </div>
    </div>
</footer>

<script src="{% static 'assets/scripts/all.min.js'%}"></script>
<script src="{% static 'assets/scripts/jquery.min.js'%}"></script>
<script src="{% static 'assets/plugin/bootstrap/js/bootstrap.min.js'%}"></script>
<script src="{% static 'assets/plugin/nprogress/nprogress.js'%}"></script>

<script src="{% static 'assets/scripts/main.js"'%}></script>

</body>

</html>